### ISSUE TITLE
Fix the warnings while compiling Solidity contracts

### ISSUE THREAD

**Issue by Flouse** [synapseweb3/ibc-solidity-contract#19]
see https://github.com/synapseweb3/ibc-solidity-contract/actions/runs/5709524579/job/15468457656#step:7:216

**Comment by jjyr** [comment]
https://github.com/synapseweb3/ibc-solidity-contract/pull/35

Another warning is raised from our dependencies https://github.com/ibc-solidity/solidity-stringutils/blob/master/src/strings.sol#L45 IMO we can leave it for now
